<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Betway Affiliate</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f4f4f4;
        }
        header {
            background-color: #333;
            color: #fff;
            padding: 10px 0;
            text-align: center;
        }
        nav {
            background-color: #444;
            padding: 10px;
            text-align: center;
        }
        nav a {
            color: #fff;
            margin: 0 15px;
            text-decoration: none;
        }
        nav a:hover {
            text-decoration: underline;
        }
        main {
            padding: 20px;
        }
        footer {
            background-color: #333;
            color: #fff;
            text-align: center;
            padding: 10px 0;
            position: fixed;
            bottom: 0;
            width: 100%;
        }
    </style>
</head>
<body>
    <header>
        <h1>Welcome to Betway!</h1>
    </header>
    <nav>
        <a href="#home">Home</a>
        <a href="#offers">Offers</a>
        <a href="#contact">Contact</a>
    </nav>
    <main>
        <section id="home">
            <h2>Home</h2>
            <p>Sign up and enjoy exclusive betting offers.</p>
        </section>
        <section id="offers">
            <h2>Offers</h2>
            <p>Check out our latest betting offers and promotions.</p>
        </section>
        <section id="contact">
            <h2>Contact</h2>
            <p>If you have any questions, feel free to contact us at <a href="mailto:support@betway.com">support@betway.com</a>.</p>
        </section>
    </main>
    <footer>
        <p>&copy; 2025 Betway. All rights reserved.</p>
    </footer>
</body>
</html>
